export const singaporeContexts = {
  shopping: [
    'NTUC FairPrice',
    'Giant',
    'Cold Storage',
    'Sheng Siong',
    'Prime Supermarket',
    'Don Don Donki',
    'Mustafa Centre',
    'Popular Bookstore',
    'Daiso',
    'Value Dollar',
  ],
  transport: [
    'MRT',
    'public bus',
    'school bus',
    'taxi',
    'private bus',
    'LRT',
    'Grab car',
    'shuttle bus',
    'double-decker bus',
    'express bus',
  ],
  food: [
    'chicken rice',
    'roti prata',
    'nasi lemak',
    'laksa',
    'satay',
    'char kway teow',
    'mee goreng',
    'curry puff',
    'kaya toast',
    'chilli crab',
    'carrot cake',
    'hokkien mee',
    'fish ball noodles',
    'mee siam',
    'rojak',
    'ice kacang',
    'popiah',
    'otah',
  ],
  places: [
    'Orchard Road',
    'Tampines Mall',
    'Jurong East',
    'Bishan Junction',
    'Marina Bay Sands',
    'Gardens by the Bay',
    'Sentosa',
    'East Coast Park',
    'VivoCity',
    'Changi Airport',
    'Jewel Changi',
    'Suntec City',
    'Botanic Gardens',
    'Bugis Junction',
    'NEX Shopping Mall',
    'Singapore Zoo',
    'Universal Studios',
    'Clarke Quay',
  ],
  schools: [
    'primary school',
    'secondary school',
    'tuition centre',
    'school library',
    'community centre',
    'junior college',
    'polytechnic',
    'ITE college',
    'enrichment centre',
    'student care centre',
  ],
  activities: [
    'badminton session',
    'swimming lesson',
    'piano class',
    'art class',
    'tuition class',
    'soccer practice',
    'dance class',
    'Chinese lesson',
    'coding workshop',
    'math olympiad',
  ],
  festivals: [
    'Chinese New Year',
    'Hari Raya',
    'Deepavali',
    'Mid-Autumn Festival',
    'National Day',
    'Christmas',
    'Vesak Day',
    'Thaipusam',
  ],
  hawkerFood: [
    'bowl of fishball noodles',
    'plate of chicken rice',
    'serving of nasi lemak',
    'bowl of laksa',
    'plate of char kway teow',
    'serving of carrot cake',
    'bowl of bak kut teh',
    'plate of economic rice',
    'bowl of yong tau foo',
    'serving of thunder tea rice',
  ],
  drinks: [
    'teh tarik',
    'kopi',
    'bandung',
    'milo dinosaur',
    'sugar cane juice',
    'soya bean milk',
    'bubble tea',
    'lime juice',
    'grass jelly drink',
    'coconut water',
  ],
  neighborhoods: [
    'Ang Mo Kio',
    'Tampines',
    'Woodlands',
    'Yishun',
    'Bedok',
    'Jurong West',
    'Sengkang',
    'Punggol',
    'Clementi',
    'Toa Payoh',
  ],
  currency: 'SGD',
  currencySymbol: '$',
  commonPrices: {
    hawkerFood: [3, 4, 5, 6, 7, 8],
    drinks: [1.2, 1.5, 2, 2.5, 3],
    transport: [1.5, 2, 2.5, 3, 3.5],
    snacks: [1, 1.5, 2, 2.5],
  },
};
